### ISSUE TITLE
Why does the screen accelerate on some computers, while others slow down.

### ISSUE THREAD

**Issue by LeonidasHypnos** [hlorenzi/mahnesjs#2]
Is there any way to unify their speed？

**Comment by hlorenzi** [comment]
I'm not totally sure since I haven't worked on this for years, but it's probably because I'm not checking the delta-time argument passed to the `requestAnimationFrame` callback, [in the `runFrameJS` function](https://github.com/hlorenzi/mahnesjs/blob/master/src/main.js#L247). The code is assuming the callback is executed at 60 fps, so if your system runs it differently, you might see slow-downs or speed-ups.
